### ISSUE TITLE
Docs: Vue mentioned, but actually react front-end

### ISSUE THREAD

**Issue by iLLucionist** [litestar-org/litestar-fullstack#128]
### Summary

Here and there (such as repo description here) Vue is mentioned, but this is a React front-end, judging from package.json. Am I missing something? Was this or will this be in Vue?

**Comment by ejbt11** [comment]
It was previously a Vite + Vue front-end. The documentation has not been updated yet as the front-end is still in a WIP.

**Comment by iLLucionist** [comment]
Interesting, thanks! Can you comment on why React was/is preferred over Vue for this example repo? (not to start a discussion on front-end frameworks).

**Comment by ejbt11** [comment]
As far as I understand, the author created this repo for backend/full-stack best practices with Litestar. Vue can replace the front end as it uses a Vite plugin. The codes are still evolving and it's a very good reference and boilerplate. 

Cofin, the author, can answer you why he migrated from Vue to React in their discord. The team behind this repo is very active and responds immediately in Discord.

**Comment by iLLucionist** [comment]
Thank you!

**Comment by cofin** [comment]
Thanks @ejbt11 this summarizes everything pretty well.  The main reason that React was chosen is due to the popularity.  However, this will work with any frontend framework that is compatible with `vite`.  I could show a few more examples in the `litestar-vite` plugin repository/README.

I've also updated the documentation.

Closed by #130

**Comment by Jackiexiao** [comment]
hi, we should update doc here as well 

https://docs.litestar.dev/2/

<img width="940" alt="image" src="https://github.com/litestar-org/litestar-fullstack/assets/18050469/b09d30f8-0003-44de-8aa1-84523ad2ce29">
