### ISSUE TITLE
Bug: Request stuck when authentication error occurs with multipart form data upload and guards/auth middleware enabled

### ISSUE THREAD

**Issue by v3ss0n** [litestar-org/litestar-fullstack#189]
### Description:

We have encountered a bug where when using guards or auth middleware with multipart-formdata file upload, the request gets stuck in an infinite loop if an authentication error occurs. The issue only occurs when a file is included in the multipart-formdata request.

Also it is only happening in fullstack , tried will vanilla litestar and it is ok.

**Expected Behavior:**

The request should fail with an authentication error on the first try and subsequent tries. It should not get stuck in an infinite loop.

**Observed Behavior:**

The request gets stuck in an infinite loop on subsequent tries after the first authentication error.

### MCVE

```python
https://github.com/HM3IT/litestar-fullstack/blob/203bedb22d5258931403d93709c640dd607d765a/src/app/domain/accounts/controllers/users.py#L141
```

### Steps to reproduce

```bash
1. Upload a file using a multipart-formdata request.
2. Include a Bearer header with an invalid authentication token/key.
3. The first request will return an authentication error and fail.
4. On subsequent tries, the request will get stuck in an infinite loop, never returning a response.
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Package Version

tested latest commit : 00be067cdad9b8ee2ef845f45f08083943db0dfe

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
Please move this to Litestar with a full MCVE.

This should not be in fullstack as it appears you've extended the code with additional functionality.
