### ISSUE TITLE
Bug: default "camel" rename_strategy in DTO causes issues

### ISSUE THREAD

**Issue by 0xSwego** [litestar-org/litestar-fullstack#66]
### Description

The default `"camel"` rename_strategy assigned in `dto.py` breaks routes in which there are camelCase parameters.

### MCVE

DTOs:
```py
@dataclass
class PasswordUpdate:
    old_password: str
    new_password: str

class PasswordUpdateDTO(DataclassDTO[PasswordUpdate]):
    config = dto.config()
```

Endpoint:
```py
    @patch(
        operation_id="UpdatePasswordUser",
        name="users:update_password",
        path=urls.USER_PASSWORD_UPDATE,
        dto=PasswordUpdateDTO,
        return_dto=None,
    )
    async def update_users_password(
        self, data: DTOData[PasswordUpdate], users_service: UserService, current_user: User
    ) -> None:
        """Update the currently logged user password."""
        current_password = data._data_as_builtins["old_password"]
        new_password = data._data_as_builtins["new_password"]
        await users_service.update_password(current_password, new_password, current_user)
```

Test:
```py
    # This will return 400 as the incoming data is expected to be in camelCase and validation will fail.
    response = await client.patch(
        "/api/me/update-password",
        json={"old_password": "old-password", "new_password": "new-password"},
    )

    # This passes validation, but it will return 500 as data._data_as_builtins is an empty dictionary
    response = await client.patch(
        "/api/me/update-password",
        json={"oldPassword": "old-password", "newPassword": "new-password"},
    )
```

### Temporary fix

I ended up removing the default `rename_strategy` from `dto.py` and stick to camel_case in and out. I think that this is the behavior devs expect (less magic, more happiness) and works out of the box.

![image](https://github.com/litestar-org/litestar-fullstack/assets/21270278/3811a2fc-bff7-4ffe-b4e1-1f52d1a4bddb)

### Litestar Version

In `2.0.0b4` gave some problems, but it worked (hence the workaround `data._data_as_builtins["xx"]` instead of `xx = data.create_instance()`, as the latter didn't work)

`2.0.0rc1` broke it completely

### Platform

- [X] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by v3ss0n** [comment]
@cofin does this still happen ?

**Comment by Goldziher** [comment]
@v3ss0n a good first contributions would a PR with a test suite testing the above behavior. If it cannot be reproduced, we can close the issue, otherwise a followup PR would be required (not necessarily by you).

**Comment by Goldziher** [comment]
do you want me to assign you the issue? @v3ss0n

**Comment by v3ss0n** [comment]
> @v3ss0n a good first contributions would a PR with a test suite testing the above behavior. If it cannot be reproduced, we can close the issue, otherwise a followup PR would be required (not necessarily by you).

I am going to test it , it would be my 2nd contribution to main repo if it efects in litestar i will fix it.

**Comment by cofin** [comment]
@v3ss0n can we close this one?

**Comment by PholphatPhumkaew** [comment]
Okay 👌

**Comment by cofin** [comment]
This should be resolved upstream.  Please re-open if it's still a problem.
