### ISSUE TITLE
Enhancement: Optimize database testing pipeline

### ISSUE THREAD

**Issue by 0xSwego** [litestar-org/litestar-fullstack#73]
### Description

I've been working with this framework for a while and added around 300 tests. On my machine, it currently takes 18 minutes to run all 300 tests, that is quite unacceptable.

I've checked what takes this long and discovered that, in the test setup:
- the `create_app()` call, in `@pytest.fixture(name="app")` takes 1s
- seeding the db takes 1.25s (the db currently has 32 models)

This means that to run 300 tests, the system needs 11+ minutes just to create the app and seed the db (62% of the execution time), that arguably can be done once at the beginning instead of each time.

### Screenshots

![image](https://github.com/litestar-org/litestar-fullstack/assets/21270278/a27a185d-490b-4b88-ba13-504efd0a7193)

### Litestar Version

2.0.1

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
I agree it can be optimized.  I've classified this as an enhancement since there is no actual error at this time.  If you've come up a working solution from your code base, a PR would be welcomed.
