### ISSUE TITLE
Bug: not compatible with any stable version of Litestar

### ISSUE THREAD

**Issue by sfermigier** [litestar-org/litestar-fullstack#76]
### Description

Tests fail when updated to either Litestar 2.0.0 or 2.1.0.

### Steps to reproduce

```bash
1. Update litestar to either 2.0.0 or 2.1.0
2. Run `make test`
```

### Litestar Version

2.0.0 or 2.1.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
Resolved by #78
