### ISSUE TITLE
Bug: default behaviour change in CollectionFilter breaks id filter

### ISSUE THREAD

**Issue by bpereto** [litestar-org/litestar-fullstack#88]
### Description

the change of the default behaviour of `CollectionFilter` in https://github.com/jolt-org/advanced-alchemy/issues/51 breaks the current implementation of `provide_id_filter` https://github.com/litestar-org/litestar-fullstack/blob/06c0b5f2e19d08fac76a1a8c1542d75e2385c167/src/app/lib/dependencies.py#L53

Currently, there is an empty list if no id's are provided in the field_name `id`.
By default, I don't want the ID filter to apply and get all results.

Would it be needed to check if a query value for "ids" is provided and only then returning a CollectionFilter instance?

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Litestar Version

litestar==2.2.1
advanced-alchemy==0.3.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
I've got a fix I'll push for this shortly.
